### ISSUE TITLE
Implement an Axon Server plugin to be able to manipulate events in Axon Server console.

### ISSUE THREAD

**Issue by zambrovski** [holixon/axon-avro-serializer#68]
In order to use the Axon Server console, which allows to search for events, a non-binary representation as simple JSON is required. The server OSGi plugin should deliver this functionality.

**Comment by jangalinski** [comment]
maybe this will be helpful: https://discuss.axoniq.io/t/looking-for-an-example-of-a-simple-axon-server-plugin/3417

**Comment by zambrovski** [comment]
see https://github.com/holixon/axon-avro-serializer/pull/93

**Comment by zambrovski** [comment]
implemented by 66e8700332729ce872ec7cd93f399ddc33a3e44e
